version: "3"

services:
  # Redis服务
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - image_generator_network

  # 后端API服务
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - image_generator_network

  # 工作进程服务
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    command: python worker.py --concurrency=3
    depends_on:
      - redis
      - api
    restart: unless-stopped
    networks:
      - image_generator_network

volumes:
  redis_data:

networks:
  image_generator_network:
    driver: bridge
